### PR TITLE
Testing Ruby code Tic-tac-toe

### PR DESCRIPTION
**Pull request by Mihndim2020**
In this project, we defined tests for the tic-tac-toe game using RSpec

### CODE REVIEW

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ✍️

Hello @Mihndim2020 and @German-Cobian, you have done a great job with your RSpec test so far. I'll like to commend you and highlight your excellence in these areas:

- Good use of git-flow
- All tests are green 🟢
- Your commit messages are very descriptive, kudos
- You did an excellent job covering tests for all public methods and also testing for reverse scenarios 👏💯

## To Improve

You did quite great in this project but there are minor issues with your repository, please fix these and resubmit it for review.

- [ ] You seem to have cleared out your `README` file and left only the part talking about how to run the test, please update your `README` file to include instructions on how to use this repo and include a test section.
- [ ] You have committed files that are not related to this project into your git, please un-track these files and add them to your `.gitignore` file. an example is the `.DS_Store` file.
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))


### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Comment by Mihndim2020** [comment]
Changes implemented as requested

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ✍️

Good improvement in your README 👏

## To Improve
- [ ] You have added `.DS_Store` to your `.gitignore` file, however git is still keeping track of them because they had been committed already. To remove these files from being tracked by git run this command on your project's root directory.
`git rm <filename>`. e.g, `git rm .DS_Store` and `git rm bin/.DS_Store`. This article may be helpful. [here](https://devconnected.com/how-to-delete-file-on-git/)

Please implement this change and resubmit for review.

Happy coding, stay motivated, stay positive.

### You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.

**Comment by Mihndim2020** [comment]
>DS_store removed from being tracked

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @charlyeneh @German-Cobian ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request closed without merging**
